FROM "dunglas/frankenphp:sha-c884d26-php8.2-alpine@sha256:2f6867715bfae5dcfa53c4d815d0dd71b75cc082f28963403568099c2ed949d9" as frankenphp_upstream
FROM composer/composer:2-bin AS composer_upstream

ARG GIT_REPO_USER
ARG GIT_REPO_USER_PASSWORD

# Base FrankenPHP image
FROM frankenphp_upstream AS frankenphp_base

WORKDIR /app

# Install all required dependencies,php extension and composer
RUN apk --no-cache add git autoconf make g++ php82-pecl-xdebug redis-cli && \
    install-php-extensions pgsql pdo_pgsql intl xdebug && \
    pecl install --onlyreqdeps --force redis && \
    docker-php-ext-enable redis && \
    rm -rf /tmp/pear;

RUN echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.mode=debug" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.client_host=host.docker.internal" >> /usr/local/etc/php/conf.d/xdebug.ini

COPY ci/frankenphp/Caddyfile /etc/caddy/Caddyfile

COPY composer.json .
COPY composer.lock .
COPY symfony.lock .

# https://getcomposer.org/doc/03-cli.md#composer-allow-superuser
ENV COMPOSER_ALLOW_SUPERUSER=1
ENV PATH="${PATH}:/root/.composer/vendor/bin"

COPY --from=composer_upstream /composer /usr/bin/composer

# prevent the reinstallation of vendors at every changes in the source code
RUN set -eux;

