ingressInternal:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "16m"
  scriptFileName:
    enabled: false
    fileName: ""
  ingressClassName: "nginx-internal"
  hosts:
    - host: dc-cia-additional-product-store
      paths:
        - path: /
          port: 80
          pathType: ImplementationSpecific
  tls: []

ingressExternal:
  enabled: false
  annotations: {} # docs at https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/
  scriptFileName:
    enabled: false
    fileName: ""
  ingressClassName: "nginx-external"
  hosts: []
  tls: []

resources:
  requests:
    cpu: 100m
    memory: 128Mi

envVars:
  SHELL_VERBOSITY: "2"
  APP_ENV: "prod"
  REDIS_HOST: "10.253.55.19:6379,10.253.55.20:6379,10.253.55.21:6379,10.253.55.22:6379,10.253.55.23:6379,10.253.55.24:6379"
  HTTPS: "off"

envSecrets:
  - name: appenv
    path: app/dc-additional-product-store-reader/appenv
    keys:
      - DATABASE_DSN
